### ISSUE TITLE
How to deploy the reinforcement learning pickle file onto the robot?

### ISSUE THREAD

**Issue by ml-boringtao** [PacktPublishing/Artificial-Intelligence-for-Robotics#11]
I rewrote the reinforcement code to make it work and then save it as a pickle file as instructed. However, there is no further instruction how I should deploy the pickle file on the robot on the book. Can you please show me some hints or reference links for doing so?

Thanks
Tao

**Comment by FGovers** [comment]
Hello:Can  you tell me which chapter you are referring to?  
The trained model is loaded in Keras using model = load_model(MODEL_PATH)

Thanks!
Francis Govers
    On Sunday, February 16, 2020, 01:12:39 PM PST, Xinghui Tao <notifications@github.com> wrote:  
 
 
I rewrote the reinforcement code to make it work and then save it as a pickle file as instructed. However, there is no further instruction how I should deploy the pickle file on the robot on the book. Can you please show me some hints or reference links for doing so?

Thanks
Tao

**Comment by XinghuiTao** [comment]
Hi Francis

It is in the chapter 5 with Indexed Q-learning (page 159). 

Thanks a lot
Tao
