### ISSUE TITLE
The  Chapter 4, what should I do when I get the CSV file?

### ISSUE THREAD

**Issue by RichardLiuSiYuan** [PacktPublishing/Artificial-Intelligence-for-Robotics#12]
I labeled the image and get the xml file,convert it into csv file ,after this i don't know what to do next, in 
your code, i don't know where the csv file are mentioned, could you plz help me and solve my problem

**Comment by sarvesh-packt** [comment]
Hey TheGreatWizards,
With regards to your query, you can read first paragraph on page nos. 119 and 120 in the book. Also, you'll need this link for resolving your issue:
https://github.com/tzutalin/labelImg/tree/master/data
 
Thanks,
Sarvesh

**Comment by RichardLiuSiYuan** [comment]
> 
Thanks for your kindly reply.
