### ISSUE TITLE
Not Documented

### ISSUE THREAD

**Issue by djovanoski** [PacktPublishing/Artificial-Intelligence-for-Robotics#3]
Dear Sir, 

I just followed all the hardware and software requirements , putting the robot all together as i buy was great but other components : how to connect Arduino Mega 2560 microcontroller  and Pololu Micro Maestro Servo Controller x6? How to start the tests if everything is good. I have offline trained CNN for object detection so how we get the result back in to the robot .

Thanks ,

**Comment by djovanoski** [comment]
Any update?

**Comment by FGovers** [comment]
zfjsbsnodki:  there are several ways to connect the MicroMaestro. What I did was to connect it to the Raspberry Pi via the USB port - this worked much better than connecting it to the USB port on the Arduino.  I apologize for any confusion.

If you prefer to attach the MicroMaestro to the Arudino, you can follow these directions:
https://www.pololu.com/docs/0J40/5.h.5

regards,
Francis Govers

**Comment by FGovers** [comment]
PS. The notifications from this page were directed to the wrong person. I'm sorry for the delay. We'll do better going forward.  I've forked the respository to allow users like to you contribute code, and I'll be providing future updates.
Francis Govers

**Comment by mfkenson** [comment]
@FGovers I really appreciate your work. I ordered the same hardware and plan to reproduce the exact same software/hardware stack. You mentioned ROS in the first chapter however I can't find the robot specific stuff e.g. URDF / catkin workspace. I do want to build the stuff from scratch and make my own ROS-compatible robot car and arm. It would be much easier to follow if you could share the ROS stuff as well. Again, thank you!
