### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by joekh1** [PacktPublishing/Artificial-Intelligence-for-Robotics#4]
can I use any board running ubuntu with ros ,without ubiquity, connected to an arduino board instead of using raspberry pi?

thank you,

best regards,
joe

**Comment by FGovers** [comment]
No an arduino will not work.  You need a linux computer.  I've used the Raspberry Pi, and the Odriod XU4, but any number of ROS-compatable boards may work.  An Arduino does not run Linux.
