### ISSUE TITLE
Arduino codes

### ISSUE THREAD

**Issue by joekh1** [PacktPublishing/Artificial-Intelligence-for-Robotics#5]
Dear Sir,

Can you please share the arduino files for a better follow up in your book?

thank you,

best regards,
Joe

**Comment by mfkenson** [comment]
I found the author forked repo:

https://github.com/FGovers/Artificial-Intelligence-for-Robotics/blob/master/Chapter01/robotMotorControl.ino

**Comment by MurtazaTinwala** [comment]
Hi @joekh1 

Please check Chapter 1 code files.

Regards,
