### ISSUE TITLE
Qlearn Script not working as expected

### ISSUE THREAD

**Issue by leocorp96** [PacktPublishing/Artificial-Intelligence-for-Robotics#7]
Correct me if I'm wrong but it seems there is a typo in **line 156 of the "armTrainingQlearn.py"** and **line 149 of the "armTrainingQlearn2.py"** which causes the script to seem like it is learning but I do not think it is because fixing this "typo", thus
-**changing**: _maxStat_ = thisStateQ
-**to**: _maxState_ = thisStateQ

Causes the training to oscillate between just 2 and/ or sometimes 3 states out of the 27 states present in the Qmatrix.

Please help with a fix or at least share some more clarification as to why I am obtaining these results.
Thank you.

**Comment by FGovers** [comment]
I'm looking into this.  I agree that the typo is there - the variable should be MaxState.  Now looking into why this is not returning the expected results.  I ran through several iterations with the debugger and this will need more investigation.

**Comment by FGovers** [comment]
I will get back to you with more information. THANKS for catching this
